# Generated by Django 3.0.2 on 2020-01-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
    ]
