# Generated by Django 3.0.2 on 2020-01-30 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('qty', models.IntegerField()),
                ('acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Account')),
            ],
        ),
        migrations.CreateModel(
            name='StockPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans', models.CharField(max_length=5)),
                ('ticker', models.CharField(max_length=5)),
                ('qty', models.IntegerField()),
                ('stock_value', models.FloatField()),
                ('acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Account')),
            ],
        ),
    ]
